@HOST = http://localhost:3333
@AUTHORIZATION = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE5MzkxMzEwLCJleHAiOjE2MTk5OTYxMTB9.CLlCZ-JYJgZiQZ5wAmxs4zEkGfo-Z6zGL1N3FAwmLUY

### Login
POST {{HOST}}/sessions
Content-Type: application/json

{
  "email": "admin@fastfeet.com",
  "password": "123456"
}

### Check
GET {{HOST}}/sessions
{{AUTHORIZATION}}


### Register
POST {{HOST}}/users
Content-Type: application/json
{{AUTHORIZATION}}

{
  "name": "Ajhgdj AJhvd DJHvd DJHJH",
  "email": "ahhsgfhsgfhas@fastfeet.com",
  "password": "12345678"
}

